apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: twitter-producer
  name: twitter-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twitter-producer
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: twitter-producer
    spec:
      containers:
        - image: 349463221567.dkr.ecr.us-east-1.amazonaws.com/twitter-producer:IMAGE_VERSION
          name: twitter-producer
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
          volumeMounts:
            - mountPath: /data
              name: producer-data
      volumes:
        - name: producer-data
          emptyDir: {}