apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: twitter-consumer
  name: twitter-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twitter-consumer
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: twitter-consumer
    spec:
      containers:
        - image: 349463221567.dkr.ecr.us-east-1.amazonaws.com/twitter-consumer:IMAGE_VERSION
          name: twitter-consumer
          imagePullPolicy: Always
          ports:
            - containerPort: 8091
          volumeMounts:
            - mountPath: /data
              name: consumer-data
      volumes:
        - name: consumer-data
          emptyDir: {}