apiVersion: v1
kind: Service
metadata:
  name: twitter-search
  labels:
    app: twitter-search
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8092
  selector:
    app: twitter-search
