apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: twitter-app
  region: us-east-1

nodeGroups:
  - name: ng-1
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        # provide role access to the app to running on EC2 instance
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAcces s
        - arn:aws:iam::aws:policy/AmazonKinesisFullAccess
        - arn:aws:iam::aws:policy/AmazonOpenSearchServiceFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/SecretsManagerReadWrite

    instanceType: t2.small
    desiredCapacity: 2
    ssh:
      publicKeyName: ec2-va
